### ISSUE TITLE
Use `git submodules to move the binary files into another repo rewriting the history

### ISSUE THREAD

**Issue by KOLANICH** [RHVoice/RHVoice#125]
The repo is damn large and is cloned damn slowly. Full rewrite of the history is needed.

for now we have settled on using submodules. We will start rewriting history as soon as we reduce the number of open pull requests to a minimum.

**Comment by zvezdochiot** [comment]
```sh
rhvoice-0.7$ du -sh .
245M	.
```

**Comment by KOLANICH** [comment]
It is too large for a repo and is completely unsuitable for CI.

**Comment by KOLANICH** [comment]
```
du -sh RHVoice
675M    RHVoice
```

And it is a shallow clone. Cloning has taken more than a hour.

**Comment by zvezdochiot** [comment]
675M ~ 245M (one shape).
You can reduce it only by dividing by:
* RHVoice
* RHVoice-data-Brazilian-Portuguese
* RHVoice-data-English
* RHVoice-data-Esperanto
* RHVoice-data-Georgian
* RHVoice-data-Kyrgyz
* RHVoice-data-Russian
* RHVoice-data-Tatar
* RHVoice-data-Ukrainian

**Comment by techtonik** [comment]
I noticed that the repo size got bigger too. I used to think that RHVoice is a small neat synthesizer, but now it looks bloated on my disk even if the binary is small. =)

I would still keep data in a separate dir, but I am no sure that it is possible now without breaking everyone's forks.

**Comment by KOLANICH** [comment]
>but I am no sure that it is possible now without breaking everyone's forks.

Then we should break them!

**Comment by alex19EP** [comment]
ok... hear are sum tests:

```
[alex@moon lfs-tests]$ time git clone https://github.com/Olga-Yakovleva/RHVoice.git
Cloning into 'RHVoice'...
remote: Enumerating objects: 91, done.
remote: Counting objects: 100% (91/91), done.
remote: Compressing objects: 100% (81/81), done.
remote: Total 13021 (delta 42), reused 27 (delta 10), pack-reused 12930
Receiving objects: 100% (13021/13021), 405.66 MiB | 12.33 MiB/s, done.
Resolving deltas: 100% (7809/7809), done.
Updating files: 100% (1578/1578), done.
git clone https://github.com/Olga-Yakovleva/RHVoice.git  17.89s user 20.33s system 83% cpu 45.629 total
[alex@moon lfs-tests]$ time git clone https://github.com/alex19EP/RHVoice RHVoice-lfs
Cloning into 'RHVoice-lfs'...
remote: Enumerating objects: 5189, done.
remote: Counting objects: 100% (5189/5189), done.
remote: Compressing objects: 100% (2602/2602), done.
remote: Total 18043 (delta 2599), reused 5154 (delta 2584), pack-reused 12854
Receiving objects: 100% (18043/18043), 404.13 MiB | 14.80 MiB/s, done.
Resolving deltas: 100% (10325/10325), done.
git clone https://github.com/alex19EP/RHVoice RHVoice-lfs  14.30s user 8.02s system 72% cpu 30.747 total
```

@KOLANICH what do you think?

**Comment by KOLANICH** [comment]
It looks like there is no gain in LFSing these files. I wonder if LFSing other binary files will give anything. Also I wonder if we can do anything else to decrease the repo size, like moving the voices out of this repo into another repo.

**Comment by maniyax** [comment]
Up, please!

We are planning to add more new voices.

In current structure repository will be very big.

**Comment by techtonik** [comment]
I approve. =)

**Comment by alex19EP** [comment]
we exported all languages and voices into separate git repos in RHVoice organization.

now we have to do the following.

- [ ] improve documentation on cloning and building with submodules #258
- [ ] notify package maintainers on infrastructure changes.
- [ ] rewrite project git histery with data as a submodules

also we will need to save the archive of the last git-tag.

also I think it is worth keeping an archive of the unmodified repository, for history. I would like to hear your opinion on this matter.

**Comment by abitrolly** [comment]
Before rewriting the history please archive old repo.

**Comment by beqabeqa473** [comment]
Yes, i agree with that.

On 2/20/21, Anatoli Babenia <notifications@github.com> wrote:
> Before rewriting the history please archive old repo.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/RHVoice/RHVoice/issues/125#issuecomment-782563234


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: beqaprogger@gmail.com
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by abitrolly** [comment]
The old archived repo is in https://github.com/RHVoice/RHVoice-legacy
