### ISSUE TITLE
update voiceBuildingUtils to py3 and fix training.pl for latest perl

### ISSUE THREAD

**Issue by beqabeqa473** [RHVoice/RHVoice#187]
hello @Olga-Yakovleva.

in latest lts release of ubuntu and some other distros, python2 is not installed by default.

what do you think about porting voice building utils to python3?

i can do a pr, but before i do, i want to know, is it needed to keep backwards compatibility with python2 or it would be possible to rewrite code to match latest python syntacs?

also in last perl versions, current working directory has been removed from @INC so config argument don't work anymore.

it is one line fix to re-add "." in Training.pl itself.

i am talking about that because there are less than year left before ubuntu 16.04 lts will stop beeing supported by canonical and more and more providers are removing this distributive from their repositories, so it would be greate to update scripts to work on newer distros.

thanks.

**Comment by Olga-Yakovleva** [comment]
I will merge such a pr if it is submitted. And no, I don't care about 
Python 2 compatibility myself.

I will also not be working on that script myself anymore. My private for 
now work among other things is to reimplement the whole thing in Python 
3 to be able to add changes and improvements myself, I'm not a Perl 
programmer and not planning to become one. So everything about the voice 
building process will change completely at some future point.

**Comment by alex19EP** [comment]
@beqabeqa473 can you fix this?

**Comment by grzezlo** [comment]
@beqabeqa473  Any progress about this issue?
I'm asking, because I can probably do it, or continue porting if you have some partial work done...

**Comment by grzezlo** [comment]
I prepared the py3 upgrade and proper Training.pl call.
Also, the guess-f0-range fix, to use f0_method configured in training.cfg, not hard-coded "sptk_rapt".
After testing i'll send it as a pull request.

**Comment by Olga-Yakovleva** [comment]
Thank you, @grzezlo. On the guess-f0-range fix though: do you have a practical reason for this? This is a very rough estimate, and sometimes not very good at that. It uses a very wide initial range, and any f0 extraction method will produce more errors in this situation. But the rough initial statistics shouldn't be too different, and rapt is the fastest. Let's say your speech corpus is large, and you are using praat_ac, which is in my experience the best pitch extraction method overall, unless your voice talent speaks with irregular phonation often or in certain contexts, such as ends of sentences, which is unfortunately not uncommon. Then you will just have to wait for a long time for Praat, with maybe a minor change in the resulting range estimate.

**Comment by zstanecic** [comment]
Hi olga,

Numbers are not minimal, I’ve tested with reaper, and f0 extracted using other methods are giving sometimes results worse than better.

Some methods, as you said handle some intonation cases differently, and reaper sometimes does the good job for us, for example, when we are talking about guessing f0 range.

Somebody who has good hearing, can confirm the difference with voices trained after the different f0 guessing and extraction steps.

**Comment by Olga-Yakovleva** [comment]
OK, but then I'd prfer to have those two settings separate, not to 
switch things back and forth for different tasks if I don't want to use 
the same method for both. So, could you please introduce something like 
guess_f0_method setting?

**Comment by grzezlo** [comment]
Thanks @Olga-Yakovleva for guess-f0 clarifications.
I was sure, that for logical reasons, the f0-extraction method should be identical as method used in F0 guessing.
Your points makes sense.
It's my mistake to do different things in one PR, I'll restore the default sptk_rapt in guess-f0, and maybe introduce the guess_f0_method for ease of experimenting, in separate PR.
Returning to Py3 conversion: why are the .hed and bpf.txt files open explicitly in binary mode, being text files in fact?
In py3 it forces some string-to-bytes conversions, which can be avoided by changing the file mode to text (default).
Can i change file mode, or should I force the string to bytes conversions?
First method is more readable, but maybe second is needed for some reasons unknown by me.

After changing file mode to text, and processing make-questions and extract-bap steps, generated files are identical to old ones.

```
with open(os.path.join(qstdir,"questions_qst001.hed"),"wb") as f_out:
		with open(os.path.join("data","bpf.txt"),"wb") as fp:

```

**Comment by Olga-Yakovleva** [comment]
I am never sure about this text mode business myself, to be honest. I 
don't think Linux system itself does anything special in text mode. I 
seem to remember Windows may do something related to new lines. But this 
will be run on Linux, so it shouldn't create any issues I think.
