### ISSUE TITLE
crash when speech-dispatcher's emoji preprocessing is used

### ISSUE THREAD

**Issue by alex19EP** [RHVoice/RHVoice#255]
## repro steps

1. add `SymbolsPreprocFile "emojis.dic"` directive in `/etc/speech-dispatcher/speechd.conf`
2. move cursor to any emoji, for example 🎄

## what happens

RHVoice crashes.

## what should be happen

RHVoice would speak the emoji.

**Comment by Olga-Yakovleva** [comment]
I've pushed a fix, please test.

**Comment by alex19EP** [comment]
fix confirmed.
