### ISSUE TITLE
Support for RHvoice voices

### ISSUE THREAD

**Issue by elnursamedzade** [RHVoice/RHVoice#262]
Hello there.  Can you provide support for the Azerbaijani language?  I've done an Azeri synthesizer with marytts before.  I really want to work with RHvoice.  can you help me?

**Comment by beqabeqa473** [comment]
hello.

if you did a language, you should have language analizer module, and speaker recordings with equivalent texts.

so, you should be able to provide everything listed above, and maybe it will be possible to adapt language module for rhvoice.

**Comment by elnursamedzade** [comment]
Yes, before that I made a synthesizer in my language with marytts. I need
rhvoice to use it with Android. Can you help me?

beqa gozalishvili <notifications@github.com>, 20 Şub 2021 Cmt, 09:30
tarihinde şunu yazdı:
