### ISSUE TITLE
How to install RHVoices on Linux?

### ISSUE THREAD

**Issue by DgDays** [RHVoice/RHVoice#264]
Good day!  Met with a problem installing voices on Linux.  I used to work with the Russian set of voices on Windows and everything was fine, but on Linux I do not know how to properly install the voices so that python packages can see them.  Help me please

**Comment by DgDays** [comment]
Yes, by the way, he sees the voices, but he separates them only by languages ​​that do not work, and as such he does not notice voices

**Comment by alex19EP** [comment]
pleas provide more info:

1. what distribution are you using?
2. how do you use rhvoice with python on windows?
