### ISSUE TITLE
Error installing RH Voice

### ISSUE THREAD

**Issue by legolego** [RHVoice/RHVoice#267]
I'm trying to install RHVoice 1.2.3 but I'm getting an error.
My NVDA version is 2020.3
I have no other addons installed.
![image](https://user-images.githubusercontent.com/1666188/107554832-75cb5300-6ba4-11eb-960a-52153ccf1ba2.png)
![image](https://user-images.githubusercontent.com/1666188/107554844-79f77080-6ba4-11eb-93b5-c6ed2674cc0d.png)
Is there something I can check? Thank you very much!

**Comment by alex19EP** [comment]
first can you replace screenshots with text of errors?
main RHVoice dev and I blind. so screenshots really won't help us solve the problem.

also describe how you install the add-on? have you installed at least one voice? it would be good to add logs as well.

**Comment by legolego** [comment]
Sure, yes.
I installed the RH Voice 1.2.3 through Manage-Addons and it was ok.
After restarting NVDA 2020.3, I went to Preferences , Settings, Speech, and try to change the synthesizer to be RH Voice.  I see it as an option, but when I choose it, I get a windows titled Synthesizer Error, with a message that says: Could not load the RHVoice synthesizer. I tried changing the Audio output device and ducking mode options, but I still get the same error. I have been able to install other synthesizer addons without issue, but they don't handle Russian. I'm trying for find a solution for mu uncle in Russia who is going blind. I haven't installed any voices. Do they come with RHVoice, or should they be installed separately? Where can I get them? Thank you very much! :)

**Comment by alex19EP** [comment]
> I haven't installed any voices. Do they come with RHVoice, or should they be installed separately? Where can I get them?

you can get voices from https://github.com/RHVoice/RHVoice/blob/master/doc/en/Binaries.md you need to install at least one.

**Comment by legolego** [comment]
Ok, thank you! :) Yes, I installed a language and now I was able to choose RHVoice. Could you change the error message to ask if the user has a RHVoice language already installed? I'm still learning all the files and addons to NVDA. Thank you very much for your help! :)
