### ISSUE TITLE
compatibility with NVDA 2021.1

### ISSUE THREAD

**Issue by fernando-jose-silva** [RHVoice/RHVoice#272]
when installing the new alpha version of nvda 21895, i noticed an incompatibility with nvda, nvda does not pronounce various information during windows navigation, the lines are cut.
As I understand it, nvda has made changes that affect the voice add-ons.
I'm not a programmer so unfortunately I don't know how to say anything else.
I would also like to apologize, I speak Portuguese and this text is translated on google.
I use the Portuguese voice Leticia.
I would like to ask you to please provide compatibility with the new versions of nvda.
Your complement is very important.
Thank you very much.

**Comment by alex19EP** [comment]
hello @fernando-jose-silva we plan to make RHVoice compatible with next version of NVDA.

this work will begin when first NVDA beta is released.

**Comment by fernando-jose-silva** [comment]
thank you very much for the return, anxious! laughs.

Enviado do Email para Windows 10

De: Alexander Epaneshnikov
Enviado:segunda-feira, 15 de março de 2021 15:53
Para: RHVoice/RHVoice
Cc:fernando-jose-silva; Mention
Assunto: Re: [RHVoice/RHVoice] main add-in compatibility with alpha versionsof nvda (#272)

hello @fernando-jose-silva we plan to make RHVoice compatible with next version of NVDA.
this work will begin when first NVDA beta is released.

**Comment by Nikita34196** [comment]
привет. есть ли возможность выпустить новую версию до выхода первой betta nvda 2021? я использую alfa версии. в последних rhvoice практически не работает. изза несовместимости стало невозможно практически использовать nvda с rhvoice

**Comment by beqabeqa473** [comment]
@Nikita34196 вы можете заменить до выхода официального релиза драйвер из pr который прикреплен к issue.

**Comment by Nikita34196** [comment]
@beqabeqa473@beqabeqa473 благодарю

**Comment by fernando-jose-silva** [comment]
please, what is the download link for the version compatible with nvda 2021 i am not very familiar with github And from what i noticed on the project page the download link still points to version 1.2.3 thank you very much.

**Comment by alex19EP** [comment]
> 
> 
> please, what is the download link for the version compatible with nvda 2021 i am not very familiar with github And from what i noticed on the project page the download link still points to version 1.2.3 thank you very much.

hello. for now you can get addon from: https://alex19ep.me/public/RHVoice/RHVoice-1.2.4.nvda-addon

I think Olga will update our file with links in the near future.

**Comment by fernando-jose-silva** [comment]
thank you very much, spectacular!

Enviado do meu iPhone
