### ISSUE TITLE
Is there documentation how to integrate RHVoice with Orca?

### ISSUE THREAD

**Issue by yurivict** [RHVoice/RHVoice#292]
Or could you please add instructions to README?

Thank you,
Yuri

**Comment by alex19EP** [comment]
you just need to install speech-dispatcher module. and that all.
instructions for compiling are at: doc/en/Compiling-on-Linux.md

**Comment by yurivict** [comment]
> you just need to install speech-dispatcher module. and that is all.

After this, how to instruct Orca to use RHVoice module instead of others?

**Comment by alex19EP** [comment]
> 
> 
> > you just need to install speech-dispatcher module. and that is all.
> 
> After this, how to instruct Orca to use RHVoice module instead of others?

you need to select RHVoice in orca settings.

**Comment by yurivict** [comment]
Thanks!
