### ISSUE TITLE
all Downloads from bintray.com fails with "Forbidden!" error

### ISSUE THREAD

**Issue by VeH-c** [RHVoice/RHVoice#299]
links in doc/en/Binaries.md and doc/ru/Binaries.md aren't working anymore

**Comment by alex19EP** [comment]
we need to move binary artifacts for windows elsewhere.

**Comment by maniyax** [comment]
Primarily artifacts for android.

**Comment by Olga-Yakovleva** [comment]
I've updated the links in the Android app. Please, people who can build that from source, confirm if the downloads are working there for you. I'll be uploading the other files in the meantime.

**Comment by Olga-Yakovleva** [comment]
I've replaced the links to the current binaries.

**Comment by beqabeqa473** [comment]
I can confirm links in the android app are working as expected by
installing build from GH actions

On 5/5/21, Olga Yakovleva ***@***.***> wrote:
> I've replaced the links to the current binaries.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/RHVoice/RHVoice/issues/299#issuecomment-832819166


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by alex19EP** [comment]
ok links in doc/en/Binaries.md and doc/ru/Binaries.md are working now, so I closing this.

**Comment by Olga-Yakovleva** [comment]
Just an explanation why there is no update through Google Play yet. I've published it yesterday, and Google are still reviewing it, whatever that means. So waiting for their approval.
