### ISSUE TITLE
SCons не компилирует модуль для Speech-Dispatcher (RaspberryPi4)

### ISSUE THREAD

**Issue by Myrkalf** [RHVoice/RHVoice#311]
RaspberryPi4, Raspbian, 
установлены GCC 8.3.0,  pkg-config 0.29, SCons 3.0.1.7, pulseaudio 12.2, speech-dispatcher 0.9.0
git clone был запущен с флагом --recurse-submodules

при компиляции SCons не проверил Speech-dispatcher и не создал sd_rhvoice, в папке /usr/local/bin лежит только RHVoice-test.
соответственно, симлинк из мануала не на что делать.

начало вывода SCons:

pi@rpi4-01:~/RHVoice $ scons
scons: Reading SConscript files ...
Mkdir("build/linux")
Georgian language is skipped because of non-free license
Checking whether the C compiler works... (cached) yes
Checking whether the C++ compiler works... (cached) yes
Checking for pkg-config... (cached) yes
Checking for libpulse-simple... (cached) no
Checking for ao... (cached) no
Checking for portaudio-2.0... (cached) no
('Configuring ', '/home/pi/RHVoice/src/core/config.h.in', 'into', '/home/pi/RHVoice/src/core/config.h', '...')
('Configuring ', '/home/pi/RHVoice/src/include/core/config.h.in', 'into', '/home/pi/RHVoice/src/include/core/config.h', '...')
scons: done reading SConscript files.
scons: Building targets ...
(ну и т.д.)

**Comment by alex19EP** [comment]
> Checking for libpulse-simple... (cached) no

это значит, что pulceaudio не найден. возможно нужно поставить что-то вроди libpulse-dev

**Comment by zstanecic** [comment]
@alex19EP 
Да, либо libpulse-dev, либо libpulsesimple-dev точное название пакета не помню,
может быть, 
@beqabeqa473 
знает больше?

**Comment by Myrkalf** [comment]
> > Checking for libpulse-simple... (cached) no
> 
> это значит, что pulceaudio не найден. возможно нужно поставить что-то вроди libpulse-dev

такого пакета (libpulse-simple) нет в системном репозитории. 
libpulse-dev не был установлен - исправлено.
при запуске scons-скрипта (после установки libpulse) в его выводе ничего не изменилось.

вопрос изначально был в том, что **scons пропускает проверку наличия speech-dispatcher и не компилирует модуль sd-rhvoice**. зависит ли это от наличия/отсутствия libpulse-simple?

самое забавное, что месяц назад я уже поднимал эту связку, и она адекватно работала, причем без особых "танцев с бубнами". но на "малинке" загнулась sd-карта, а её дамп я сделать не успел. и теперь всё приходится поднимать заново.
но в прошлый раз было много экспериментов и проб других opensource голосовых движков, в итоге которых я и пришел к rhvoice. очень бы не хотелось повторять все эти метания.

**Comment by beqabeqa473** [comment]
он пропускает sd, потомучто видит что не установлены аудио зависимости.

On 6/10/21, Myrkalf ***@***.***> wrote:
>> > Checking for libpulse-simple... (cached) no
>>
>> это значит, что pulceaudio не найден. возможно нужно поставить что-то
>> вроди libpulse-dev
>
> такого пакета (libpulse-simple) нет в системном репозитории.
> libpulse-dev не был установлен - исправлено.
> при запуске scons-скрипта (после установки libpulse) в его выводе ничего не
> изменилось.
>
> вопрос изначально был в том, что **scons пропускает проверку наличия
> speech-dispatcher и не компилирует модуль sd-rhvoice**. зависит ли это от
> наличия/отсутствия libpulse-simple?
>
> самое забавное, что месяц назад я уже поднимал эту связку, и она адекватно
> работала, причем без особых "танцев с бубнами". но на "малинке" загнулась
> sd-карта, а её дамп я сделать не успел. и теперь всё приходится поднимать
> заново.
> но в прошлый раз было много экспериментов и проб других opensource голосовых
> движков, в итоге которых я и пришел к rhvoice. очень бы не хотелось
> повторять все эти метания.
>
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/RHVoice/RHVoice/issues/311#issuecomment-858413076


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by Myrkalf** [comment]
> он пропускает sd, потому что видит что не установлены аудио зависимости.
так а какой пакет ему нужен? libpulse-dev установлен.
в установке Libao или PortAudio смысла не вижу - PulseAudio стоит и работает в системе по умолчанию.

скрипт scons при повторном запуске не надо каким-либо образом предварительно переинициализировать? или он каждый раз "как в первый раз" запускается и проверяет зависимости?

**Comment by beqabeqa473** [comment]
попробуйте очистить working directory и заново запустите scons

On 6/10/21, Myrkalf ***@***.***> wrote:
>> он пропускает sd, потому что видит что не установлены аудио зависимости.
> так а какой пакет ему нужен? libpulse-dev установлен.
> в установке Libao или PortAudio смысла не вижу - PulseAudio стоит и работает
> в системе по умолчанию.
>
> скрипт scons при повторном запуске не надо каким-либо образом предварительно
> переинициализировать? или он каждый раз "как в первый раз" запускается и
> проверяет зависимости?
>
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/RHVoice/RHVoice/issues/311#issuecomment-858575034


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by alex19EP** [comment]
> > > Checking for libpulse-simple... (cached) no
> > 
> > 
> > это значит, что pulceaudio не найден. возможно нужно поставить что-то вроди libpulse-dev
> 
> @alex19EP ,
> такого пакета (libpulse-simple) нет в системном репозитории.
> libpulse-dev не был установлен - исправлено.

вот это должно помочь. давайте правда попробуем очистить дерево исходников `git clean -xdf`
и повторим компиляцию.

> при запуске scons-скрипта (после установки libpulse) в его выводе ничего не изменилось.
> 
> вопрос изначально был в том, что **_scons пропускает проверку наличия speech-dispatcher и не компилирует модуль sd-rhvoice_**. зависит ли это от наличия/отсутствия libpulse-simple?
> 

угу. для компиляции модуля sd на данный момент нужна какая либо звуковая библиотека.

> самое забавное, что месяц назад я уже поднимал эту связку, и она адекватно работала, причем без особых "танцев с бубнами". но на "малинке" загнулась sd-карта, а её дамп я сделать не успел. и теперь всё приходится поднимать заново.
> но в прошлый раз было много экспериментов и проб других opensource голосовых движков, в итоге которых я и пришел к rhvoice. очень бы не хотелось повторять все эти метания.

я думаю путём проб и ошибок мы сможем сделать это.

**Comment by Myrkalf** [comment]
окей,
git clean -xdf     <-done 

установленные в системе пакеты (флаги: i - установлено, A - автоматически):

i   gcc							- GNU C compiler
i   gcc-4.9-base					- GCC, the GNU Compiler Collection (base package)
i   gcc-5-base						- GCC, the GNU Compiler Collection (base package)
i   gcc-6-base						- GCC, the GNU Compiler Collection (base package)
i   gcc-7-base						- GCC, the GNU Compiler Collection (base package)
i A gcc-8							- GNU C compiler
i   gcc-8-base						- GCC, the GNU Compiler Collection (base package)
i A libgcc-8-dev					- GCC support library (development files)
i   libgcc1							- GCC support library
i   pkg-config						- manage compile and link flags for libraries
i   scons							- replacement for make

i A pulseaudio						- PulseAudio sound server
i A pulseaudio-module-bluetooth		- Bluetooth module for PulseAudio sound server
i A pulseaudio-utils					- Command line tools for the PulseAudio sound server
i   libpulse-dev					- PulseAudio client development headers and libraries
i A libpulse-mainloop-glib0			- PulseAudio client libraries (glib support)
i A libpulse0						- PulseAudio client libraries
i A libpulsedsp					- PulseAudio OSS pre-load library
i A libao-common					- Cross Platform Audio Output Library (Common files)
i   libao-dev						- Cross Platform Audio Output Library Development
i A libao4							- Cross Platform Audio Output Library
i   libportaudio-dev					- Portable audio I/O - development files
i A libportaudio0					- Portable audio I/O - shared library
i A libportaudio2					- Portable audio I/O - shared library
i   speech-dispatcher				- Common interface to speech synthesizers
i A speech-dispatcher-audio-plugins	- Speech Dispatcher: Audio output plugins
i A speech-dispatcher-espeak			- Speech Dispatcher: Espeak output module
i A speech-dispatcher-espeak-ng		- Speech Dispatcher: Espeak-ng output module`

(как тут каты делать?)

запускаю scons:

pi@rpi4-01:~/RHVoice $ scons
scons: Reading SConscript files ...
Mkdir("build/linux")
Georgian language is skipped because of non-free license
Checking whether the C compiler works... yes
Checking whether the C++ compiler works... yes
Checking for pkg-config... yes
Checking for libpulse-simple... yes
Checking for ao... yes
Checking for portaudio-2.0... no
Checking Speech Dispatcher version ... no
('Configuring ', '/home/pi/RHVoice/src/core/config.h.in', 'into', '/home/pi/RHVoice/src/core/config.h', '...')
('Configuring ', '/home/pi/RHVoice/src/include/core/config.h.in', 'into', '/home/pi/RHVoice/src/include/core/config.h', '...')
scons: done reading SConscript files.
scons: Building targets ...
...
scons: done building targets.

как видно, он не увидел speech-dispatcher, хотя последний в системе есть и нормально работает, даже говорит дурным голосом espeak.
какие варианты?

**Comment by alex19EP** [comment]
> как видно, он не увидел speech-dispatcher, хотя последний в системе есть и нормально работает, даже говорит дурным голосом espeak.
какие варианты?

думаю поставить libspeechd-dev.
p.s. вот за это я не люблю дебиан.
p.ss. спойлеры можно делать на html
```html
<details>
  <summary>какие-то данные</summary>
  
  тут много текста.
  
</details>
```

**Comment by beqabeqa473** [comment]
нужно поставить development library speechd
libspeechd-dev
иначе он не сможет найти заголовок и проверить версию.

On 6/10/21, Alexander Epaneshnikov ***@***.***> wrote:
>> как видно, он не увидел speech-dispatcher, хотя последний в системе есть и
>> нормально работает, даже говорит дурным голосом espeak.
> какие варианты?
>
> думаю поставить libspeechd-dev.
> p.s. вот за это я не люблю дебиан.
> p.ss. спойлеры можно делать на html
> ```html
> <details>
>   <summary>какие-то данные</summary>
>
>   тут много текста.
>
> </details>
> ```
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/RHVoice/RHVoice/issues/311#issuecomment-858768543


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by Myrkalf** [comment]
о! 
доустановка libspeechd-dev помогла!
после перезапуска scons-скрипта он наконец-таки увидел Speech-dispatcher и скомпилировал модуль для работы с ним.
работоспособность проверена, движок работает.
<details>
  <summary>итак, для установки на Raspberry Pi 4 (Raspbian) нужны:</summary> 
  - обязательные:<br>
  gcc<br>
  libgcc-[номер_версии]-dev<br>
  pkg-config<br>
  scons<br>
  - вариативный для управления:<br>
  speech-dispatcher<br>
  libspeechd-dev<br>
  - один из наборов:<br>  
  pulseaudio<br>
  libpulse-dev<br>
   или<br>
  libao4<br>
  libao-dev<br>
   или<br>
  libportaudio2<br>
  libportaudio-dev<br>
</details>

alex19EP, спасибо за помощь!
