### ISSUE TITLE
update CLDR to the latest version

### ISSUE THREAD

**Issue by zstanecic** [RHVoice/RHVoice#312]
Hi to all,
This is specially interesting for 
@alex19EP 
and
@Olga-Yakovleva 
I have prepared the pull request whic updates the submodule of the unicode CLDR data to the latest version.
In that way, RHvoice emoji support will be the same as we have it directly included in NVDA.
From this change, mostly benefits all android devices running RHVoice and also the linux platform.
What do you think? 
Best,
Zvonimir

**Comment by alex19EP** [comment]
this is good, but it is not enough just to update cldr, you also need to create new versions of language packs, and change one cpp file.

in fact I would wait until a new version of unicode is released.

**Comment by zstanecic** [comment]
It’s not a problem as I will do it.

Beqa just told me how to do it.

Waiting for the new Unicode is not an option, as these data are dynamically updated.

**Comment by zstanecic** [comment]
Hi Alexandr,
As i have tested myself that all changes made, not just downloading, but compiling emoji data works, can i proceed with the update and make the pr?

**Comment by alex19EP** [comment]
> Hi Alexandr,
> As i have tested myself that all changes made, not just downloading, but compiling emoji data works, can i proceed with the update and make the pr?

sure.

**Comment by zstanecic** [comment]
Ok. I will do it as soon as possible.
Thanks,
Zvonimir
