### ISSUE TITLE
Silencing in some symbol combinations

### ISSUE THREAD

**Issue by outsidepro-arts** [RHVoice/RHVoice#333]
I've just tested the latest action build which uses new speed control and accured with situations when RHVoice either silences in strings when something symbols combination exists, or the reading suddenly interrupts. Unfortunately, i have no a combinations which RHVoice silences, but I have combination which the synthesizer interrupts while reading:
 07q
Ььььь
Получено в 09:49

**Comment by zstanecic** [comment]
I can reproduce the problem with soft sign symbols only.

**Comment by outsidepro-arts** [comment]
Agree also with hard sign symbols. I suspect that the interrupting bug appears when a string contains two or more symbols which the engine should process, but does not soundable representation.

**Comment by outsidepro-arts** [comment]
Just one more thing: when these symbols presented as word. For example:
This ьь string
This ъъ string - these examples will be interrupted. Thiьs string
Thiъs string
- these examples will be read.

**Comment by alex19EP** [comment]
are you sure it started after the 2880abe16ada461b8bda76f822d7a2faa9766c49 commit?

can someone do a [git bisect](https://git-scm.com/docs/git-bisect)?

**Comment by outsidepro-arts** [comment]
I've used the latest releases both on PC and on Android. I'd not saw this behavior there. I've used the debug builds while working in a collaboration with RHVoice Lab, so i may suppose that I didn't tested all commits list. But now I'm testing the new speed control and found this.

**Comment by alex19EP** [comment]
unfortunately I cannot reproduce the problem. RHVoice does not read 5 soft characters in a row, but RHVoice reads the entire string "fooьььььbar".

**Comment by Olga-Yakovleva** [comment]
The problem with the soft and hard signs should be solved by #338. Other possible problems have been mentioned here as well, but there is not enough information about them.
