### ISSUE TITLE
please add German language

### ISSUE THREAD

**Issue by starbrights** [RHVoice/RHVoice#334]
As far as I know this is only free Android TTS system not depending on Google Play Services. Please add German as language. Thank you

**Comment by alex19EP** [comment]
> As far as I know this is only free Android TTS system not depending on Google Play Services.

I think [espeak-ng](https://github.com/espeak-ng/espeak-ng)
can be installed without google play too.

> Please add German as language.

unfortunately we are not ready to accept requests to add new languages. sorry.

**Comment by starbrights** [comment]
Thanks for the hint. 
I tested some. The best I could find was tflite. While it is availabe in FDroid, it contains an German/Austrian only in Google PlayStore - just as a hint to others looking for that. If someone find any better - please let me know.

**Comment by IzzySoft** [comment]
@starbrights see #24 – and yeah, eSpeak is not really useable for German, though the F-Droid version can be set to German (but that sounds quite horrible; rarely bearable with variant NVDA (Jacky), speed 152WPM). I didn't try TFLite, though. To my knowledge, those 3 are all that can be found in the FOSS world ([see here](https://android.izzysoft.de/applists/category/named/office_speech) for my list) – if I missed any, I'm all ears.
