### ISSUE TITLE
scons OSError on Arch Linux

### ISSUE THREAD

**Issue by ChickenKiddie** [RHVoice/RHVoice#381]
`[~/build/RHVoice]$ scons scons: Reading SConscript files ... 
Mkdir("build/linux") 
Georgian language is skipped because of non-free license 
OSError: 'pkg-config speech-dispatcher --variable=modulebindir' exited 1: 
  File "/home/ck/build/RHVoice/SConstruct", line 373: 
    vars=create_user_vars() 
  File "/home/ck/build/RHVoice/SConstruct", line 169: 
    vars.Add(PathVariable("spd_module_dir", "Speech dispatcher module directory", get_spd_module_dir(),  PathVariable.PathAccept)) 
  File "/home/ck/build/RHVoice/SConstruct", line 96: 
    return env.ParseConfig("pkg-config speech-dispatcher --variable=modulebindir", passthru) 
  File "/usr/lib/python3.9/site-packages/SCons/Environment.py", line 1640: 
    return function(self, self.backtick(command)) 
  File "/usr/lib/python3.9/site-packages/SCons/Environment.py", line 585: 
    raise OSError("'%s' exited %d" % (command, status))`
    
I installed RHVoice on my other archbox but this error came up on this one, I tried to understand what's going on but to no avail..

**Comment by alex19EP** [comment]
Did you used pkgbuild from AUR?

**Comment by ChickenKiddie** [comment]
> Did you used pkgbuild from AUR?

I didn't use pkgbuild, here I thought I already installed rhvoice with yay while I actually did not previously notice that the install was not finalized and that there was an error, so I did sudo rm -rf /usr/lib/speech-dispatcher.service and later /usr/lib/speech-dispatcher-modules/rhvoice which solved the problem.
