### ISSUE TITLE
Not install RHVoice

### ISSUE THREAD

**Issue by Mazhit76** [RHVoice/RHVoice#382]
(env) mazhit@DESCTOP-IMG:~/Desctop/RHVoice$ scons
scons: Reading SConscript files ...
Mkdir("build/linux")
Georgian language is skipped because of non-free license
Package speech-dispatcher was not found in the pkg-config search path.
Perhaps you should add the directory containing `speech-dispatcher.pc'
to the PKG_CONFIG_PATH environment variable
No package 'speech-dispatcher' found
OSError: 'pkg-config speech-dispatcher --variable=modulebindir' exited 1:

**Comment by alex19EP** [comment]
you need to install libspeechd-dev if you on debian or ubuntu

**Comment by Mazhit76** [comment]
Ubuntu. Добрый день. Благодарю за ответ. Вопрос решил.

**Comment by savoptik** [comment]
@alex19EP Could you please add this information to the build instructions?
