### ISSUE TITLE
Unsupported library version

### ISSUE THREAD

**Issue by Tippman** [RHVoice/RHVoice#384]
Hello!

When I'm trying to create mp3 - catch an error:

> Warning! Unsupported library version, use API 1.2.0. Supported: ('0.7.2', '1.0.0', '1.2.0', '1.2.1', '1.2.2', '1.2.3'), library: 1.4.2.

**Comment by alex19EP** [comment]
can you provide mor info?

* what platform are you using
* how you creating mp3 file

**Comment by beqabeqa473** [comment]
It is related to RHVoice python wrapper.
I think you should open an issue against https://github.com/Aculeasis/rhvoice-proxy

However at the time of my answer it supports 1.4.2
