### ISSUE TITLE
artifacts are not created in Ci and code ql of the project doesn't work

### ISSUE THREAD

**Issue by zstanecic** [RHVoice/RHVoice#401]
Title says it all. Compilation of test versions of the synthesizer is not working when triggered by push. It says, that error is on line 42 of the codeql analysis file.

**Comment by zstanecic** [comment]
cc
@alex19EP

**Comment by alex19EP** [comment]
> cc @alex19EP

FYI no need to mention me I receive all activity in this repo and organization.

**Comment by zstanecic** [comment]
Ok
