### ISSUE TITLE
Marianna voice for Android

### ISSUE THREAD

**Issue by Symbian9** [RHVoice/RHVoice#406]
Add Marianna voice for Android (APK)

- https://github.com/RHVoice/RHVoice/commit/b38f5891ec8a885cfc1493281a7d061a26680cce
  - https://github.com/RHVoice/RHVoice/blob/master/doc/ua/Binaries.md#%D1%83%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%81%D1%8C%D0%BA%D0%B0-2
  - https://github.com/RHVoice/RHVoice/blob/master/doc/en/Binaries.md#ukrainian-2

**Comment by alex19EP** [comment]
for this we need to release a new version.

**Comment by Symbian9** [comment]
> for this we need to release a new version.

If so, how manually install voice on Android from `data.zip`?

- https://github.com/RHVoice/marianna-ukr/releases/tag/4.0

**Comment by alex19EP** [comment]
you can't do that, but you can download prebuilt app from: https://github.com/RHVoice/RHVoice/suites/3959426466/artifacts/99450360
