### ISSUE TITLE
I cannot build project on raspberry os

### ISSUE THREAD

**Issue by savoptik** [RHVoice/RHVoice#428]
Hello. I did everything according to the [instructions](https://github.com/RHVoice/RHVoice/blob/master/doc/en/Compiling-on-Linux.md), but after executing the ```$ scans```, I received an error, "src/include/core/config.h" was not found.

**Comment by alex19EP** [comment]
please provide full scons output.

**Comment by savoptik** [comment]
```shel
pi@raspberrypi:~/build/RHVoice $ scons
scons: Reading SConscript files ...
Mkdir("build/linux")
Georgian language is skipped because of non-free license
Checking whether the C compiler works... yes
Checking whether the C++ compiler works... yes
Checking for pkg-config... yes
Checking for libpulse-simple... yes
Checking for ao... yes
Checking for portaudio-2.0... no
Checking Speech Dispatcher version ... yes
('Configuring ', '/home/pi/build/RHVoice/src/core/config.h.in', 'into', '/home/pi/build/RHVoice/src/core/config.h', '...')
('Configuring ', '/home/pi/build/RHVoice/src/include/core/config.h.in', 'into', '/home/pi/build/RHVoice/src/include/core/config.h', '...')
IOError: [Errno 2] No such file or directory: '/home/pi/build/RHVoice/data/voices/aleksandr-hq/voice.info':
  File "/home/pi/build/RHVoice/SConstruct", line 382:
    build_for_linux(base_env,vars)
  File "/home/pi/build/RHVoice/SConstruct", line 340:
    duplicate=0)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 614:
    return method(*args, **kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 551:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 256:
    call_stack[-1].globals)
  File "/home/pi/build/RHVoice/data/SConscript", line 46:
    props=RHVoiceInfoParser.parse(subdir.File(type+".info").abspath)
  File "/home/pi/build/RHVoice/site_scons/RHVoiceInfoParser.py", line 10:
    with io.open(path,"rt",encoding="utf-8") as f:
pi@raspberrypi:~/build/RHVoice $ 
```

**Comment by beqabeqa473** [comment]
initialize submodule with git submodule update --init

On 12/29/21, Artem Semenov ***@***.***> wrote:
> ```shel
> ***@***.***:~/build/RHVoice $ scons
> scons: Reading SConscript files ...
> Mkdir("build/linux")
> Georgian language is skipped because of non-free license
> Checking whether the C compiler works... yes
> Checking whether the C++ compiler works... yes
> Checking for pkg-config... yes
> Checking for libpulse-simple... yes
> Checking for ao... yes
> Checking for portaudio-2.0... no
> Checking Speech Dispatcher version ... yes
> ('Configuring ', '/home/pi/build/RHVoice/src/core/config.h.in', 'into',
> '/home/pi/build/RHVoice/src/core/config.h', '...')
> ('Configuring ', '/home/pi/build/RHVoice/src/include/core/config.h.in',
> 'into', '/home/pi/build/RHVoice/src/include/core/config.h', '...')
> IOError: [Errno 2] No such file or directory:
> '/home/pi/build/RHVoice/data/voices/aleksandr-hq/voice.info':
>   File "/home/pi/build/RHVoice/SConstruct", line 382:
>     build_for_linux(base_env,vars)
>   File "/home/pi/build/RHVoice/SConstruct", line 340:
>     duplicate=0)
>   File "/usr/lib/scons/SCons/Script/SConscript.py", line 614:
>     return method(*args, **kw)
>   File "/usr/lib/scons/SCons/Script/SConscript.py", line 551:
>     return _SConscript(self.fs, *files, **subst_kw)
>   File "/usr/lib/scons/SCons/Script/SConscript.py", line 256:
>     call_stack[-1].globals)
>   File "/home/pi/build/RHVoice/data/SConscript", line 46:
>     props=RHVoiceInfoParser.parse(subdir.File(type+".info").abspath)
>   File "/home/pi/build/RHVoice/site_scons/RHVoiceInfoParser.py", line 10:
>     with io.open(path,"rt",encoding="utf-8") as f:
> ***@***.***:~/build/RHVoice $
> ```
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/RHVoice/RHVoice/issues/428#issuecomment-1002721790
> You are receiving this because you are subscribed to this thread.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili
