### ISSUE TITLE
Support Mongolian language

### ISSUE THREAD

**Issue by AlexRK7** [RHVoice/RHVoice#434]
Hello! 
We are official dealer of UCS Rkeeper products in Mongolia. And UCS products use RHVoice voice synthesizer. How can we cooperate to support Mongolian language?

**Comment by alex19EP** [comment]
lets ask @Olga-Yakovleva

**Comment by AlexRK7** [comment]
Hello! @Olga-Yakovleva . How can we cooperate?

**Comment by Olga-Yakovleva** [comment]
@AlexRK7 could you contact me privately by email? olga@rhvoice.org

**Comment by Olga-Yakovleva** [comment]
Moved to a private discussion.
