### ISSUE TITLE
Voice pitch in the polish voices

### ISSUE THREAD

**Issue by zstanecic** [RHVoice/RHVoice#442]
Hi,
When the polish language was converted to the data only format, we have lost the pitch rised in the exclamation and interrogative sentences. We used the combination of pitchmod decision tree borrowed from macedonian, and the question tagger.
We also had the fragment of the code:
  void polish::post_lex(utterance& u) const
  {
    relation& sylstruct_rel=u.get_relation("SylStructure");
    for(relation::iterator word_iter(sylstruct_rel.begin());word_iter!=sylstruct_rel.end();++word_iter)
      {
        item& last_syl=word_iter->last_child();
        if(last_syl.has_prev())
          last_syl.prev().set<std::string>("stress","1");
        else
          last_syl.set<std::string>("stress","1");
      }
  }
}
This code, in combination with pitch-mod worked to have the intonation on every question and exclamation. This worked before polish was converted to data only, and we noticed it after the conversion.
The prototypes  (beta experiments of various polish voices are located in my and 
@grzezlo
repositories, respectively..
Best,
Zvonimir

**Comment by Olga-Yakovleva** [comment]
This issue was opened by my request, but I was wrong in making it. The fix needs to be implemented in the Polish language code, not in RHVoice. see #441 for more information. So closing.
