### ISSUE TITLE
voice building discussion, edited

### ISSUE THREAD

**Issue by king-dahmanus** [RHVoice/RHVoice#447]
ok, so there was a new us english voice released on android, her name is lyubov. I consider her the best us voice ever available in rh voice. But when I checked for the windows packages, there's no lyubov for nvda or sapi. Why is that? And will you add this voice? Thanks

**Comment by zstanecic** [comment]
Hi,

Lyubov is available here

https://www.rhvoice.su

**Comment by king-dahmanus** [comment]
Thanks! I've got it! I wish I could make my own english voice :smiles:. Can I record some sentenses and send them to the team somehow so they can manually build my voice? Where do I find the required sentences to record? I want to ready the dataset so I can send it to the team so they can manuallly build it, as I don't have linux experience, good hardware etc?

**Comment by king-dahmanus** [comment]
what does this change do?

**Comment by king-dahmanus** [comment]
oh it justs adds a doc ok
