### ISSUE TITLE
Failed to compile under windows.

### ISSUE THREAD

**Issue by elnursamedzade** [RHVoice/RHVoice#494]
Hello again.
Compilation fails under Windows.
I am getting the following output:

scons: Reading SConscript files ...
Mkdir("build\windows")
Checking for WiX toolset(cached) yes
Checking for NSIS(cached) yes
Mkdir("build\windows\x86")
Configuring the build system for x86
Checking for Visual C++ ... (cached) yes
Visual C++ version is 14.0
Checking whether the C compiler works... (cached) yes
Checking whether the C++ compiler works... (cached) yes
Checking for pkg-config... (cached) no
Configuring  C:\Users\Elnur\RHVoice\src\core\config.h.in into C:\Users\Elnur\RHVoice\src\core\config.h ...
Configuring  C:\Users\Elnur\RHVoice\src\include\core\config.h.in into C:\Users\Elnur\RHVoice\src\include\core\config.h .
..
Mkdir("build\windows\x86_64")
Configuring the build system for x86_64
Checking for Visual C++ ... (cached) yes
Visual C++ version is 14.0
Checking whether the C compiler works... (cached) yes
Checking whether the C++ compiler works... (cached) yes
Checking for pkg-config... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
msgfmt -c -o build\windows\nvda-addon\locale\ru\LC_MESSAGES\nvda.mo src\nvda-addon\locale\ru\LC_MESSAGES\nvda.po
'msgfmt' is not recognized as an internal or external command,
operable program or batch file.
scons: *** [build\windows\nvda-addon\locale\ru\LC_MESSAGES\nvda.mo] Error 1
scons: building terminated because of errors.

I guess it doesn't see pkg-config in my path. But I added the necessary pkg-config compiled files to the path.
When I run pkg-config with cmd, I get the following output:

Must specify package names on the command line

What am I doing wrong? Please correct me.
Thanks.

**Comment by zstanecic** [comment]
You need to add poedit tools to path.

**Comment by elnursamedzade** [comment]
@zstanecic thank you for your quick response.
Worked!
