### ISSUE TITLE
Global list of mispronounced words

### ISSUE THREAD

**Issue by TheQuinbox** [RHVoice/RHVoice#497]
I'm not sure how easy many of these would be to fix, because I'm not entirely sure how the voice processing works, but figured I'd at least start this. A list of words that RHVoice says wrong, with the way I had to add them to my NVDA  dictionary to make them say properly. Feel free to add more:

* [ ] Kylie -> Kylee
* [ ] Integer -> intijer
* [ ] Jaylin -> Jhaylin
* [ ] Gibberish -> jibberish
* [ ] Jaelyn -> Jhaylin

**Comment by TheQuinbox** [comment]
Closing this, as RHVoice does, apparently, have dictionary support. Just not sure if it works in the NVDA add-on yet.

**Comment by zstanecic** [comment]
Yes, it does. You just need to create the dictionary, edit it, and add the corresponding wrong words.
