### ISSUE TITLE
Add dictionary support.

### ISSUE THREAD

**Issue by TheQuinbox** [RHVoice/RHVoice#498]
Would close #497
If RHVoice had dictionary support, people like me could publish a dictionary file to fix all the mispronounced words, without the main code having to be modified.

**Comment by zstanecic** [comment]
RHVoice has dictionary support. You can see the dictionary support doc as an example dictionary. The descriptions are english, but example is russian

**Comment by TheQuinbox** [comment]
@zstanecic, is it possible to use these with NVDA? If so, I'll close this as fully completed.

**Comment by TheQuinbox** [comment]
Hi @zstanecic,
Where are dictionaries mentioned in docs? I've looked through the configuration file section extensively and haven't found it.
Thanks.
