### ISSUE TITLE
Not working on LineageOS 18.1 + OsmAnd

### ISSUE THREAD

**Issue by andrei-a-papou** [RHVoice/RHVoice#510]
First off, thank you for this project. 

I'd love to use it on Android, but unfortunately can't at this time. The APK from F-Droid (v1.6.0) installs fine, but I trying to even set a language under standard Android settings crashes the Settings app.

![image](https://user-images.githubusercontent.com/30468319/159122586-97b22bde-7a9a-4a97-b4a1-76abbe1c3a0d.png)

Also, speech rate and pitch sliders are disabled, indicating Android is not picking up the TTS:

![image](https://user-images.githubusercontent.com/30468319/159122606-37a00cc5-8554-4b1a-b0c7-d4fa97939307.png)
 

At the same time, I can see RHVoice is registered under "Preferred engine":

![image](https://user-images.githubusercontent.com/30468319/159122757-8e85ce87-ee7d-4837-988b-79d791698e6b.png)

I can confirm TTS doesn't work in apps, e. g. OsmAnd+. I have also tried another TTS engine called eSpeak NG and can confirm it works (however the quality is basically unusable).

I'm using LineageOS 18.1 on Xiaomi Mi A1 if that matters (Android 11). I can provide more info about the system if needed.

Can I do anything to debug the issue further?

**Comment by zstanecic** [comment]
Hi Andrei!

Which language are you trying to load?

Have you downloaded the language data from the app?

**Comment by andrei-a-papou** [comment]
Hi @zstanecic, I've downloaded and enabled Russian (Anna) and English (Evgeniy-Eng). I've tested the voices within the app to confirm they work there.

**Comment by alex19EP** [comment]
hmm. RHVoice works fine on my  girlfriend's phone with LineageOS installed.

Also, since most rhvoice developers are blind, you need to replace the screenshots with text.

**Comment by andrei-a-papou** [comment]
Alex, thanks for the answer and the clarification. I'll add text to the screenshots. In the meantime, could you tell me your girlfriend's LineageOS version as well as her phone model?

**Comment by alex19EP** [comment]
hello. LOS 18.1 build by me last month. she uses one plus 6.

just in case. can you test another apk. for example from google play or apk mirror?

**Comment by zstanecic** [comment]
Or download the app from the latest master artifacts. 

Some people told me, that this app works eve nbetter.

**Comment by andrei-a-papou** [comment]
I think I figured it out. My objective was to make RHVoice work with OsmAnd. I was constantly getting a "cannot start TTS engine" error.

Below i how I solved it.

To make RHVoice work with OsmAnd on LineageOS, follow these steps:
    - install eSpeak NG (eSpeak NG_1.51-dev.apk)
    - install RHVoice (RHVoice-v1.6.1.apk)
    - configure RHVoice, download voices, etc
    - go to "Settings > Accessibility > Text-to-speech output" and select eSpeak as a preferred engine; at this point eSpeak will initialize languages (a notification will briefly appear on the screen)
    - now select RHVoice as a preferred engine, after which it will work in OsmAnd
    - eSpeak NG can now be safely deleted

It appears that without eSpeak the TTS functionality doesn't get initialized properly and OsmAnd throws an error: "Cannot start TTS engine".

UPDATE: There seems to be a simpler workaround as explained in this comment: https://github.com/GrapheneOS/os-issue-tracker/issues/377#issuecomment-872845443

I haven't tested it, but it might be that it's not enough to install a single TTS engine; the TTS engine needs to be explicitly tapped on (even though it's the only one) to get initialized. If that's the case, obviously when two TTS engines are installed, the problem resolves itself as we toggle between eSpeak and RHVoice.

It appears to be a usability issue on stock AOSP (and LineageOS) that comes with no TTS engines by default.

**Comment by andrei-a-papou** [comment]
The Russian voices are of good quality, I'm using them in OsmAnd now and it's great for my needs. Thanks team for the awesome work!

**Comment by alex19EP** [comment]
I'm glad you were able to resolve this issue. it also explains why neither I nor my girlfriend weren't able to repeat this problem. we are both blind and of course we have several tts installed and more
over, google-tts started working even before the phone was set up.
