### ISSUE TITLE
replacing hts

### ISSUE THREAD

**Issue by king-dahmanus** [RHVoice/RHVoice#511]
Hey devs. I've hird that hts is hard to train, but at the same time, I've been told that clustergen, the hts equivalent found in festival/festvox, is much more straightforward. Is its licence free enough to replace the existing hts implimentation, or at least improve the quality of hts? Thanks

**Comment by Olga-Yakovleva** [comment]
I see no advantage in switching to Clustergen.

**Comment by king-dahmanus** [comment]
so is this part where the voices are considerably harder to train true? I'm
talking about the part where the more data you add, the more problems pop
up and you have to find a balance between consistency and clearness.
Someone who's very experienced with festvox/festival told me that
cklustergen is easier and that it doesn't have such a phenomenon
