### ISSUE TITLE
High-quality English (US) voices?

### ISSUE THREAD

**Issue by andrei-a-papou** [RHVoice/RHVoice#513]
There appears to be a high-quality female voice from Google, please take a look at https://github.com/espeak-ng/espeak-ng/issues/1090

Can this be integrated with RHVoice?

**Comment by alex19EP** [comment]
> Can this be integrated with RHVoice?

sorry but no. moreover, even if it were possible, the legality of this raises big questions.

**Comment by king-dahmanus** [comment]
it is based on hts, just like rhvoice, but I guess google modified hts to
make it sound much beter. Also it's closed sourced so yeah
