### ISSUE TITLE
segmentation fault (core dumped) on Georgian language

### ISSUE THREAD

**Issue by Olga-Yakovleva** [RHVoice/RHVoice#515]
### Discussed in https://github.com/RHVoice/RHVoice/discussions/514

<div type='discussions-op-text'>

<sup>Originally posted by **DavidTbilisi** March 21, 2022</sup>
![image](https://user-images.githubusercontent.com/14097493/159252865-8fe08141-183b-4641-a857-8e2eafc0df10.png)
Hello, I have used Georgian language, but after I suppose last update it gives me segmentation fault.
Can someone help me? 

Below are installed packages
![image](https://user-images.githubusercontent.com/14097493/159253881-f37664e3-59de-4cb3-ad13-5b2409189af8.png)
</div>

**Comment by Olga-Yakovleva** [comment]
@DavidTbilisi, Please list the exact steps to reproduce, including the input text. Please no images: they are useless to us blind developers.

**Comment by DavidTbilisi** [comment]
I'm really sorry. 

I have installed Georgian, English, Russian packages. 
Russian and English packages are working fine when I type:
echo "Hello I'm speech syntezator" |  RHVoice-test -p clb  
and
echo "Привет я синтезатор речи" |  RHVoice-test -p aleksandr-hq 
but when I type the same in Georgian
echo "გამარჯობა მე საუბრის სინტესატორი ვარ" |  RHVoice-test -p natia
it prints "segmentation fault (core dumped)"
