### ISSUE TITLE
CLDR Submodule broken

### ISSUE THREAD

**Issue by InfiniteCoder01** [RHVoice/RHVoice#581]
pi@raspberrypi:~/Dev/Raya/RHVoice $ sudo git submodule update --init --recursive
Cloning into '/home/pi/Dev/Raya/RHVoice/src/third-party/cldr'...
error: inflate: data stream error (incorrect header check)
fatal: serious inflate inconsistency
fatal: index-pack failed
fatal: clone of 'https://github.com/unicode-org/cldr.git' into submodule path '/home/pi/Dev/Raya/RHVoice/src/third-party/cldr' failed
Failed to clone 'src/third-party/cldr'. Retry scheduled
Cloning into '/home/pi/Dev/Raya/RHVoice/src/third-party/cldr'...
error: inflate: data stream error (incorrect header check)
fatal: serious inflate inconsistency
fatal: index-pack failed
fatal: clone of 'https://github.com/unicode-org/cldr.git' into submodule path '/home/pi/Dev/Raya/RHVoice/src/third-party/cldr' failed
Failed to clone 'src/third-party/cldr' a second time, aborting

**Comment by zstanecic** [comment]
Cldr was updated to the latest version already. What you try to do?

 

From: InfiniteCoder ***@***.***> 
Sent: Thursday, June 9, 2022 1:04 PM
To: RHVoice/RHVoice ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [RHVoice/RHVoice] CLDR Submodule broken (Issue #581)

 

***@***.***:~/Dev/Raya/RHVoice $ sudo git submodule update --init --recursive
Cloning into '/home/pi/Dev/Raya/RHVoice/src/third-party/cldr'...
error: inflate: data stream error (incorrect header check)
fatal: serious inflate inconsistency
fatal: index-pack failed
fatal: clone of 'https://github.com/unicode-org/cldr.git' into submodule path '/home/pi/Dev/Raya/RHVoice/src/third-party/cldr' failed
Failed to clone 'src/third-party/cldr'. Retry scheduled
Cloning into '/home/pi/Dev/Raya/RHVoice/src/third-party/cldr'...
error: inflate: data stream error (incorrect header check)
fatal: serious inflate inconsistency
fatal: index-pack failed
fatal: clone of 'https://github.com/unicode-org/cldr.git' into submodule path '/home/pi/Dev/Raya/RHVoice/src/third-party/cldr' failed
Failed to clone 'src/third-party/cldr' a second time, aborting

**Comment by InfiniteCoder01** [comment]
I am trying to compile RHVoice on my Raspberry Pi 3B. when I run sudo git clone --recursive https://github.com/RHVoice/RHVoice.git
it aborting on

**Comment by alex19EP** [comment]
don't use sudo to clone git repo.

please remove repo and try again.

**Comment by InfiniteCoder01** [comment]
When I run git clone --recursive https://github.com/RHVoice/RHVoice.git, after some cloning it breaks with message:
Cloning into '/home/pi/Dev/Raya/RHVoice/src/third-party/cldr'...
remote: Enumerating objects: 292368, done.        
remote: Counting objects: 100% (76/76), done.        
remote: Compressing objects: 100% (65/65), done.        
remote: Total 292368 (delta 29), reused 10 (delta 3), pack-reused 292292        
Receiving objects: 100% (292368/292368), 336.85 MiB | 2.81 MiB/s, done.
error: inflate: data stream error (incorrect header check)
fatal: serious inflate inconsistency
fatal: index-pack failed
fatal: clone of 'https://github.com/unicode-org/cldr.git' into submodule path '/home/pi/Dev/Raya/RHVoice/src/third-party/cldr' failed
Failed to clone 'src/third-party/cldr'. Retry scheduled
Cloning into '/home/pi/Dev/Raya/RHVoice/src/third-party/cldr'...
remote: Enumerating objects: 292368, done.        
remote: Counting objects: 100% (76/76), done.        
remote: Compressing objects: 100% (65/65), done.        
remote: Total 292368 (delta 29), reused 10 (delta 3), pack-reused 292292        
Receiving objects: 100% (292368/292368), 336.47 MiB | 2.67 MiB/s, done.
error: inflate: data stream error (invalid distance too far back)
fatal: serious inflate inconsistency
fatal: index-pack failed
fatal: clone of 'https://github.com/unicode-org/cldr.git' into submodule path '/home/pi/Dev/Raya/RHVoice/src/third-party/cldr' failed
Failed to clone 'src/third-party/cldr' a second time, aborting

**Comment by alex19EP** [comment]
hello @InfiniteCoder01 I just checked and everything works for me. check git version, internet. something else.

**Comment by InfiniteCoder01** [comment]
I've enabled the VPN on my windows machine and it cloned fine. Sorry to bother you.
