### ISSUE TITLE
Please, enable the modulation based postfilter in the training cfg

### ISSUE THREAD

**Issue by zstanecic** [RHVoice/RHVoice#609]
This is mainly to:
@Olga-Yakovleva 
# background
Now the mspf can be turned on just by patching the python file of the voice building utils, but not the training config file as well.
for example, this article:
https://www.cs.cmu.edu/~awb/papers/07393764.pdf
sheds more light on this.
I have trained successfully one voice with turned on mspf, and uncommenting the switch to train the mspf. This filter gives us more naturallness, and intelligibility at the fast speech rates, too.
# What i propose?
Giving this to be turned on by the training operator by the config, as well as silence detection feature.

**Comment by grzezlo** [comment]
As we discussed, changing it in the voice-building-utils would affect only the configure stage, so would  be not too much suitable for experiments.
This also would require to modify config.pm.in, uncommenting $TMSPF and setting proper value there.
So, better solution would be to enable or disable MSPF before training.pl, e.g. using sed as follows:

For enabling the MSPF:

```
sed -i -re 's/^(\s*\#?\s*)(\$useMSPF)\s*\=.*$/\2=1\;/g;s/^(\s*\#?\s*)(\$TMSPF)\s*\=.*$/\2=1;/g' scripts/Config.pm 
```

And to disable it, if it wouldn't work good on some voice:

```
sed -i -re 's/^(\$useMSPF)\s*\=.*$/\1=0\;/g;s/^(\s*\#?\s*)(\$TMSPF)\s*\=.*$/\2=0;/g' scripts/Config.pm 
```
