### ISSUE TITLE
CLDR 42 is released

### ISSUE THREAD

**Issue by zstanecic** [RHVoice/RHVoice#652]
# what happened?
New emoji release with their character descriptions is released. 
# proposition from my side:
upgrade it to latest version, so that people can have access to it for all languages supported, because the new emojis have been added.
I am going to update this and propagate it to all languages.
What do you think?
@Olga-Yakovleva 
@alex19EP 
@louderpages

**Comment by alex19EP** [comment]
do it

**Comment by zstanecic** [comment]
Ok. I will do it.
I ask @Olga-Yakovleva 
to update the language zips for the following languages, when i do the update:
albanian,
brazilian portuguese,
english,
georgian,
kyrgyz, or kyrghiz, i am not sure about the spelling :)
macedonian, 
Russian and ukrainian.
I will do the rest, i.e update the MSi reference via pull request to the needed submodule
