### ISSUE TITLE
Release builds for Android don't seem to ve functioning properly

### ISSUE THREAD

**Issue by Olga-Yakovleva** [RHVoice/RHVoice#658]
This breaks the latest Alpha release I made earlier today. I also checked with a manual release build. No languages are shown on the initial screen. I'm assuming the failure to get or parse the json directory. This does not happen in the dubug builds. I'll try to investigate. But it takes me away from something else I really need to be workin on right now. If anyone else can help, this will be greatly appreciated. You need to build the release version signing it with some personal key. Logging statements related to the json need to be changed to work in a release. @alex19EP, we need to develop some kind of procedure for testing release builds.

**Comment by Olga-Yakovleva** [comment]
I have disabled all the Alpha testers. Hopefully, it will prevent most of the automatic updates. @zstanecic, please warn the Polish testers just in case.

**Comment by Olga-Yakovleva** [comment]
JSON parsing fails, because Moshi is unhappy about something. I don't understand the reason. Considering that it doesn't happen in debug builds, can someone restore optimization in debug builds and see if the problem then reproduces. And in that case find with which change it started happening?

**Comment by zstanecic** [comment]
Which file is responsible for this?

I am happy to test on my isolated branch for that.

**Comment by zstanecic** [comment]
It throws errors when i try to build, and action is failing.
Maybe i am doing something wrong?
branch for my debug build is called android-update
on my fork of RHVoice.

**Comment by Olga-Yakovleva** [comment]
Tested myself that this is fixed by #659.

**Comment by Olga-Yakovleva** [comment]
The fixed version is now available in the Alpha track. The testers should check to be on the safe side that they have installed 1.10.1, not 1.10.0.

**Comment by zstanecic** [comment]
Hi!

Have you turned back on beta testers?

As a security precaution, you turned these off, as is said.

**Comment by Olga-Yakovleva** [comment]
Yes, I've enabled them again.

**Comment by zstanecic** [comment]
Strange.

I get the messages that I need to wait to re-register to the betas.

**Comment by Olga-Yakovleva** [comment]
Perhaps it takes some time for my published changes to become available 
all through their systems. Try again in a few hours. If it still doesn't 
work, please report the exact message you are seeing.
