### ISSUE TITLE
RHVoice doesn't pronounce any symbols or Acronyms

### ISSUE THREAD

**Issue by TlonUqbar** [RHVoice/RHVoice#722]
I'm using RHVoice on Linux (Pop! OS) via speech-dispatcher.  

It mostly works, but I can't get it to speak any of the symbols or acronyms.  Is there a way to get RHVoice to speak them?  

I read somewhere that a user dictionary might be the way to go, but I can't find any documentation for this.  Anyway, I hope I can get some help or info on this.

I have tried modifying the `RHVoice.conf` file settings but I'm not having a luck.

I've set punctuation to some and included these symbols "@$-+<>~%^&*|\/" but they all get ignored.
I saw somewhere that it also accepts the ascii decimal so I tried these " #61;#35;#47;#92;" as well but no luck.

Currently I have these settings
```
punctuation_mode=some
punctuation_list=@$-+<>~%^&*|\/
```

Let me know if I need to add any additional info or settings.

Any help with either will be greatly appreciated.

**Comment by zstanecic** [comment]
Hi,
Regarding symbols list and the ini file, what are your line endings? 
If your line endings are cr, it will not work, as RHVoice has a bug which prevents initializing config, if the line endings are cr.
These should be lf, or crlf.
User dictionaries are documented, but using the russian examples. The short example is located in the config folder of the source.
I thing that you need spelled acronyms, not expanded to the word level?

**Comment by TlonUqbar** [comment]
Hi thanks for the quick response,

I'm on a Linux system, and line endings are `LF`.  Also, my configuration file is not `.ini` it is `.conf` so I'm not sure if that is issue or not.

Can you point me to the documentation for user dictionaries?  
And perhaps show me how they work?  By this, I mean how they are created (what is the naming scheme, etc) , where do the need to be stored/located, and what contents should it have (settings needed or perhaps of an example).

If I can get this to work, I might be able to write an English version of the documentation with proper examples.  I can imagine I'm not the only one having this issue and I'm sure many could benefit from having that documentation in English.

**Comment by TlonUqbar** [comment]
Hi there,

So I have been able to determine that the user dictionaries are located in `/etc/RHVoice/dicts/<language>/`, what I don't know if the name I should use for the dictionary and the file extension.  Should the name by `custom-dictionary.txt` or `user.dict`?

Any chance you can give an example of the user dictionary contents?  Clearly they are key-value pairs, but can you show me what valid dictionary with 2 entry looks like?  For example, do I need to have any specific data that denotes sections, are comments allow, if so what what is the format?   

`key : value` or `key=value` or `"key" : "value"` or `"key"="value"` or `key  \t value` or `key, value`

I'm just trying to figure this out.

**Comment by TlonUqbar** [comment]
So I've had some success with this but it is still not working correctly on my linux distribution, I'm using `Pop!-OS 22.04 LTS`

First, this only works when using the `RHVoice-test` command, but it doesn't work when using "speech-dispatcher" via the   `spd-say` command.

When it comes to the creating the custom dictionary.  You have to navigate to `/etc/RHVoice/dicts/English/`
if any of the directories are missing create them  `mkdir -p /etc/RHVoice/dicts/English/`

Inside the `English` directory, create a file and name it `dictionary.txt`

The contents of the dictionary seem to follow this format `word=definition`, but they seem to only work for words of 3 letters or more. 

Also it seems to accept `'`  and `-` symbols as syllable separators e.g: `SQL=see-kwel` or `GOP=gee'oh'pee`

And it didn't complain or stopped working when using `# comments`  which is great for organizing sections `# A` or `# Symbols`

Here is example of a `dictionary.txt`
```
GOP=geeoohpee          # this works
selfies=selfees        # this works

lives=lyves   # this works
lead=leed     # this works

SQL=seekwel          # this doesn't work
lbs=pounds           # this doesn't work

Jr=junior          # this doesn't work
Dr=doctor          # this doesn't work

&=and                # doesn't work
%=percentage         # works when encountered alone
$=dollars            # this one doesn't work if it is immediately followed by a number


```

The `$` sign is an interesting case, it only seems to work when encountered alone or when escaped \$,  
if `$` followed by any number is not pronounced (ignored), it seems to think it is a reserved symbol or word 

Examples:
Using `RHVoice-test`
`$200`    is pronounced as "zero zero",
`\$200`   is pronounced as "dollars two hundred"  see my $ sign definition

Using `spd-say`
`$200`     is pronounced as "zero zero,"
`\$200`    is pronounced as "two hundred"

Interestingly enough, when using `spd-say` the `€` symbol gets proper pronunciation but when using `RHVoice-test` it just gets ignored

Using `RHVoice-test`
`€200`  is pronounced as "Two Hundred"

using `spd-say`
`€200` it is pronounced as "Euro Two Hundred"

After several more dictionary edits, some of the words started working with "speech-dispatcher" via `spd-say`

Anyway, I hope this helps out anyone having trouble with custom dictionaries.  And I hope that the developer can take a look at these things and maybe fix some of them.

**Comment by TlonUqbar** [comment]
I want to close this issue here, so I'm going to do the best I can to share with you what I have learned.  Feel free to add it to the repo's documentation in any format you want.

I had google translate, translate the documentation for the Russian custom dictionary -  [here](https://github.com/RHVoice/RHVoice/blob/master/config/dicts/Russian/example.txt) is the file take a look.  I took that output and spliced it together and added my examples and explanations.

Here is what I have been able to figure out and can confirm works, section by section and with examples.  
For the most part it is possible to combine multiple rules on any one word.  
Each of this section is a rule.

### This is not a section but it should be mentioned that comments are allowed with a  ";"  semi-colon 
```ini
; this is a comment
```


### Indication of stress directly in the word.
```ini
; Russian example
м+ало
; translation of Russian example
м+ало
```
This example wasn't of any help.  I could not find a word where I can make this work.  It is very likely I don't understand what this does or how it works.   Don't know if this works.


### Specify the pronunciation after the equal sign.
```ini
; Russian example
себе=себ+е  
; translation of Russian example
self=self+e

; English example
selfie=self+i
```
You can change the pronunciation of the syllable by adding a "+" plus sign followed by the letters that make the desired sound.  This works!


### Indication of the stressed syllable number.  A negative number means counting from the end.
```ini
; Russian examples and translations of examples
чего/2 
кого/-1
среды=среды/-1
дома=дома/1
; what/2
; whom/-1
; environments=environments/-1
; home=home/1

; English examples

```
This works.

### The task of pronunciation of names.  These rules will not apply to words written in small letters.
```ini
; Russian example
Тома=т+ома
Тому/1
; translation of Russian example
Volume=t+ohm
Volume/1

; English examples
(Git=ghit)&Hub
(Git=ghit)&hub
(git=ghit)&hub
```
I'm not entirely sure I understand this one, but I think it says that Capitalized words can get a separate pronunciation that won't be applied to the lowercase version of the word.  If this is the case this works.
In my examples, I tried "GitHub", "Github" and "github", this is compound example that will be explained later, for now let focus on the Capitalized variations.

Adding the first example will only affect the pronunciation of the word "GitHub" and the words "Github" and "github" will be unaffected and will be treated a completely different words.
Adding the second example  will only affect "Github" and leave "GitHub" and "github" unaffected.
Adding the last example will change the pronunciation of all words.



### Correction of the pronunciation "on the spot", without having to write out the whole word after the equal sign.
```ini
; Russian example
б(е=+э)та
; translation of Russian example
b(e=+e)ta

; English examples
w(i=ih)nd
(git=ghit)
```
This works.



### Set the pronunciation of several words at once with a list of alternatives.
```ini
; Russian example
лист{а,е}/-1
бр+ауз(е=э)р{,ы,а,ов,у,ам,ом,ами,е,ах}
; translation of Russian example
sheet{a,e}/-1
br + auz (e \u003d e) p {, s, a, ov, y, am, om, ami, e, ax}

; English examples
call&back{,s}
chat&room{,s}
node&list{,s}

```
I can verify that this works.  
Anything on the left of the curly braces is considered the root word.
The curly braces "{ , , ,}" have the letters that you would add the word to make a variant, like a plural or different tense.
Doing this { , s}, means the whole word is the root, and the second variant is the plural.

### An abbreviation to be spelled out.
```ini
; Russian example
чгу/i
; translation of Russian example
chgu/i

; English examples
GOP/i    
PTA/i     
ECB/i
```
All acronyms can be spelled out by adding/appending a "/i" slash lowercase 'i' to the acronym.  This works.


### Break up the word to avoid vowel reduction.
```ini
; Russian examples
егэ=е&гэ
гос&дум{а,ы,е,у,ой}
; translation of Russian examples
ege=e&ge
State & Duma {a, s, e, y, oh}

; English examples
callback=call&back{, s}
nodelist=node&list{, s}
webpage=web&page
```
This works.  Inserting an "&" ampersand in between the words forces individual pronunciation of each word.  Here I'm combining the "&" ampersand and "{,}" curly braces rules.



### A rule can start or end with  `*`.   
```ini
; Russian example
рос&телек+ом*
; translation of Russian example
ros&tele+om*
```
For example, this rule applies to any word starting with "rostelecom".

I didn't get to try this one because I couldn't find any useful examples for this.  I don't know how or if this works.




### Set the pronunciation of phrases.  Words are separated by spaces.
```ini
; Russian examples
{в,о,на} ч(е=ё)м
{во,обо,на} вс(е=ё)м
все=всё равно
{в,о} н(е=ё)м
к ч(е=ё)рту
; translation of Russian examples
{in, o, on} h (e \u003d e) m
{in, both, on} sun (e = e) m
all = anyway
{v,o} n(e=e)m
to h (e \u003d e) mouth

```
This I could not get to work at all, but I would love to get it working.  I'm sure that I'm missing something.  The examples weren't very helpful here.



### Put emphasis on the preposition and mark the next word as unstressed.
```ini
; Russian example
{на,за,под}/1 рук{у,и}/u
; translation of Russian examples
{on, behind, under} / 1 hands {y, and} / u

```
I do not know of any specific instances in English where I could use this. I couldn't test so I don't know if it works.



### In phrases, the use of the * sign is also allowed, but only at the beginning of the first or the end of the last word.
```ini
; Russian example
*{ы,и}е дом+а
; translation of Russian examples
* {s, and} e house + a

```
I do not know of any specific instances in English where I could use this. I couldn't test so I don't know if it works.



### Set the pronunciation of the character.
```ini
; Russian example
\=бэк&слэш
; translation of Russian example
\=back&slash

; English examples
\=back&slash
€=euros
£=sterling pounds
```
This works, but only if you are using the command RHVoice-test, it wonky if you are using "speech-dispatcher" service and its command `spd-say`  I'll go into greater detail below.


### Pronunciation of one of the reserved characters.
```ini
; Russian example
#/=слэш
; translation of Russian examples
#/=slash

; English examples
#@=at
#&=and
#$=dollars
##=numbers
#%=percentage
```
This works, but only if you are using the command RHVoice-test, it wonky if you are using "speech-dispatcher" service and its command `spd-say`  I'll go into greater detail below.


### Specifying a character by its code.
```ini
; Russian example
#8470=номер
; translation of Russian example
#8470=number

```
I could not verify that this works.

That covers the documented custom Russian dictionary.

---
## This next part is for Linux users

Here is some additional information that will be useful to Linux users, particularly to anyone using RHVoice via `speech-dispatcher` and its built in command `spd-say`.  

- Whenever you make any changes to the custom dictionary file, you need to restart the `speech-dispatch` service so that the changes can propagate.
- You can restart the service with this command`systemctl --user restart speech-dispatcher.service`  and you can check the status with this command `systemctl --user status speech-dispatcher.service`
- I added this alias `rhreset='systemctl --user restart speech-dispatcher.service; systemctl --user status speech-dispatcher.service'` to my `.bash_aliases`  file.  
- Then whenever I make a change to the dictionary, I simply type `rhreset` in the command line and this restarts the `speech-dispatcher` service and gets me a status report on the service.
- After that I can use `spd-say` to read the words I modified to verify the change.


### Symbols are tricky.   
This is largely dependent on your "RHVoice.conf" config file.  If you selected `punctuation_mode=all` all symbols will be spoken and you can change how any symbol is spoken.
- If you selected `punctuation_mode=some` that means that only a selected few symbols will be spoken and the rest will be ignored.  
- What actually gets spoken depends on what you've listed on   `punctuation_list=@$/\`.  
- Symbols not on this list will not be spoken and pronunciation can not be altered.

However, `speech-dispatcher` does not seem to obey this, it seems to do whatever it wants in regards to symbols.  Let me give you some examples.

First, take a look at my punctuation list from the "RHVoice.conf" file.  These are the symbols I decided that I wanted to hear spoken.
```ini
punctuation_list=+<>~@$%&*|^€£#61;#35;#47;#92;
```


First try this punctuation string with RHVoice-test.
```shell
echo "+,<,>,~,@,$,%,&,*,|, (, ), {, }, [,], €, £, \, /, = ^ ; :‎ " | RHVoice-test -p SLT 
```
  - this speaks most of it, and speaks them in the pronunciation listed in the custom dictionary
  - refer symbols sections above
  - '%'  was pronounced as 'percentage' not 'percent'
  - '£'  was pronounced as 'sterling pounds' not 'pounds'
  - '€'  was pronounced as 'euros' not 'euro'

This is what I expected!

However, I have integrated "RHVoice" with "speech-dispatcher" because this allows me to use the reader capabilities of Firefox and EBook readers like Thorium. 
I have also created a custom shortcut that takes the selected text as the input for RHVoice.
My custom command looks like this `bash -c 'xsel | spd-say -e -w -y slt -m most | pkill xsel'`.  
For now let's ignore most of that, this is the relevant part for this `spd-say -e -w -y slt -m most`   
  - -e mean pipe-mode
  - - -w means wait until the message is read or discarded, this prevents spd-say stop before it has finish reading the entire text
  - -y specifies with voice to use, SLT in this case, 
  - -m means punctuation mode and the options are (none, some, most, all), I have it set to most.

Now let's have it speak the same punctuation string as above.
```shell
spd-say "+,<,>,~,@,$,%,&,*,|, (, ), {, }, [,], €, £, \, /, = ^ ; :‎ "  # only said euro
spd-say -m some "+,<,>,~,@,$,%,&,*,|, (, ), {, }, [,], €, £, \, /, = ^ ; :‎ " # + < > @ % & * € / =
spd-say -m most "+,<,>,~,@,$,%,&,*,|, (, ), {, }, [,], €, £, \, /, = ^ ; :‎ " # + < > ~ @ % & * | ( ) { } [ ] € \ / = ^ ;
spd-say -m all "+,<,>,~,@,$,%,&,*,|, (, ), {, }, [,], €, £, \, /, = ^ ; :‎ "  # +,<,>,~,@,$,%,&,*,|, (, ), {, }, [,], €, £, \, /, = ^ ;   on the ":" colon was ommitted
# None of this is consistent with the RHVoice.conf file puntuation list
```


For the most part, I'm happy that I have been able to get some things to work the way I want, but I still have some of my original problems.
For example, I want to get some abbreviations to be spoken and I want to modify they pronunciation for some.



```ini
; None of these are prnounced/spoken, and I would like that be spoke as 'Doctor'
Dr=Doctor
DR=Doctor
Dr.=Doctor
DR.=Doctor

; Abbreviations for measurements, they get spelled out
km=kilometer
kg=kilogram
lbs=pounds
lb=pound
mi=miles
; the only one I can get to be spoken is miles, 
mi=Miles Davis
; it was spoken as "Miles Davis"

; I want to get things like GPB, USD, CAD, etc to spoken like this
USD=US Dollars
GBP=British Pounds
CAD=Canadian Dollars

AMD=Advanced Micro Devices
UK=United Kingdom
USA=United States
SQL=Sequel or Seekwel
```
None of those things work with either `RHVoice-test` or `spd-say`

Actually I just got it to say USD as "US Dollars" with this contortion
```ini
US/i&(D=Dollars)
```

**Comment by Joeviocoe** [comment]
This issue seems to be the best documentation for an English user dictionary file.  I cannot find any other good English dictionaries for RHVoice online.  Just the Russian one with translated comments, but that's not helpful unless you can read the Russian text too.

What I want to do is abbreviate numbers in English for street names in Android turn-by-turn navigation.

1200 should be pronounced twelve hundred, not one thousand two hundred.
1250 should be twelve fifty
1000 should remain one thousand

Any idea how to accomplish this with a dictionary file?
Thanks.
