### ISSUE TITLE
Android 5.1.1 and probably onwards, excluding newer android versions: 7 8 through 13

### ISSUE THREAD

**Issue by zstanecic** [RHVoice/RHVoice#728]
# problem:
Voices and languages list cannot be optained on android 5.1.1, 6, probably 7.x. The bug covers versions of RHVoice: 1.8, the first version which includes 1.12.
For example, polish language is not visible for some reason. Where can be the culprit? What can i do to investigate more 
@Olga-Yakovleva

**Comment by Olga-Yakovleva** [comment]
@zstanecic, do you have such an older device where this can be reproduced?

**Comment by zstanecic** [comment]
Hi Olga,

Yes, i do.

**Comment by zstanecic** [comment]
Closing it, because it was fixed...
