### ISSUE TITLE
Set ISO639_1_NAME2CODE_Uzbek to the code of the lang

### ISSUE THREAD

**Issue by papoteur-mga** [RHVoice/RHVoice#765]
Trying to build the latest snapshot, I get:
```
CMake Error at data/languages/CMakeLists.txt:9 (message):
  Please set ISO639_1_NAME2CODE_Uzbek to the code of the lang from
  https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
```

**Comment by artenax** [comment]
I am getting a cmake configuration error in version 1.8.0 on Linux for Polish:
```
CMake Error at data/languages/CMakeLists.txt:9 (message):
  Please set ISO639_1_NAME2CODE_Polish to the code of the lang from
  https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
```
There are no such errors in 1.6.0.

**Comment by artenax** [comment]
Add these lines to the appropriate places in data/CMakeLists.txt:
```
set("ISO639_1_NAME2CODE_Uzbek" "uz")
set("VOICE_sevinch_LANG" "uz")
```

You may also need to rename dbus.pc to dbus-1.pc.

**Comment by artenax** [comment]
I made a build for Ubuntu 16.04 i386, maybe someone will find this useful.
https://github.com/artenax/rhvoice/releases
