### ISSUE TITLE
Android compilation from master branch

### ISSUE THREAD

**Issue by Mihuilk** [RHVoice/RHVoice#778]
Trying to compile Android version (from Master branch)
I got this error : Task :RHVoice-core:BoostIncludes FAILED
Tried on both IOS and Windows platforms
looks like missing file under external/libs/boost/include/boost 
Looks like there is no boost file inside

**Comment by Mihuilk** [comment]
looks like boost library missing
which version shall be used?

**Comment by alex19EP** [comment]
have you cloned with submodules?

**Comment by Mihuilk** [comment]
Yes, I tried from command line with --recurse-submodules tag, from GitHub Desktop and from zip file.Always the error is the same
Execution failed for task ':RHVoice-core:BoostIncludes' .A problem occurred starting process 'command 'scons''

**Comment by qkqsb** [comment]
I have written documentation on the subject which has yet to be merged. See below for instructions currently written for just Linux:
https://github.com/qkqsb/RHVoice/blob/master/doc/en/Compiling-for-Android.md
If you would like to proceed using windows, you can figure out how to get scons running from here:
https://scons.org/pages/download.html

**Comment by Mihuilk** [comment]
Great, thank you for your help @qkqsb . I succeded to compile an Android a few days ago with minor changes and pre downloaded boost library. I will also try a clean build by your tutorial with scons tool.

**Comment by qkqsb** [comment]
@Mihuilk If this meets your needs, please close the issue.

**Comment by Mihuilk** [comment]
ok, thank you @qkqsb
