### ISSUE TITLE
RHVoice.conf file doesn't seem to have any effect

### ISSUE THREAD

**Issue by Kzer-Za** [RHVoice/RHVoice#795]
Or I misunderstand what it is supposed to do. I thought that the settings in that file should have effect if I run RHVoice-test without specifying the profile/rate/pitch as CLI options (-p, -r, -t).

So I have RHVoice.conf with the following content:

```
quality=max

default_volume=1.5

voices.vitaliy.default_pitch=1.0
voices.bdl.default_pitch=1.2

voices.vitaliy.default_rate=0.85
voices.bdl.default_rate=0.8

voice_profiles=vitaliy+bdl
```

Then I run `RHVoice-test -i somefile.txt -o - | aplay`, but the text is read not by "vitaliy+bdl" voices but by "alan" (which leads to the Russian section of the text not being read at all) with pitch, rate, and volume of 1.0 (as far as I can tell by how it sounds).

(I can continue this communication in Russian, if that's preferable).

**Comment by alex19EP** [comment]
hello rhvoice-test dosn't support configuration file. only speech-dispatcher module uses it.
